seed: 42

env_name: 'crash-v0'
architecture: 'DQN'
track: True
device: 'cpu'
ego_model: './E0_MOBIL.pth'

frame_stack: 1
use_mobil: True

scenarios:
  # - 'scenarios.IdleSlower'
  - 'scenarios.IdleFaster'
  # - 'scenarios.CutIn'

# NN
batch_size: 32
gamma: 0.8
start_e: 1.0
end_e: 0.05
decay_e: 6000
tau: 0.005
lr: 0.0005
buffer_size: 15000
buffer_type: 'ER'
num_hidden_layers: 1
hidden_layer: 256


total_episodes: 200
total_timesteps: 100000

save_trajectories: False
trajectory_path: "./trajectories"
