seed: 42

env_name: "crash-v0"
architecture: "DQN"
track: True
device: "cpu"

policy_A:
  - policies.DQNPolicy
policy_B:
  - scenarios.IdleSlower
  - scenarios.IdleFaster
  - scenarios.CutIn
  - scenarios.CutInSlowDown
  - policies.MobilPolicy.behind_left
  - policies.MobilPolicy.behind_right
  - policies.MobilPolicy.forward_left
  - policies.MobilPolicy.forward_right

frame_stack: 1
render: False
train_ego: True

# NN
batch_size: 32
gamma: 0.8
start_e: 1.0
end_e: 0.05
decay_e: 6000
tau: 0.005
lr: 0.0005
buffer_size: 15000
buffer_type: "ER"
num_hidden_layers: 1
hidden_layer: 256

checkpoint_testing_episodes: 10
testing_episodes: 10
total_timesteps: 100000

save_trajectories: True
root_directory: "./dqn_vs_scenarios_1stack"
trajectory_path: "episodes"
model_save_path: "models"
