seed: 42

env_name: "crash-v0"
architecture: "DQN"
track: True
device: "cpu"

policy_A:
  - policies.DQNPolicy
policy_B:
  - scenarios.IdleSlower
  - scenarios.IdleFaster
  - scenarios.CutIn
  - scenarios.CutInSlowDown
  - policies.MobilPolicy.behind_left
  - policies.MobilPolicy.behind_right
  - policies.MobilPolicy.forward_left
  - policies.MobilPolicy.forward_right

frame_stack: 5
render: False
train_ego: True

# NN
batch_size: 128
gamma: 0.8
start_e: 1.0
end_e: 0.05
decay_e: 60000
tau: 0.005
lr: 0.0005
buffer_size: 150000
buffer_type: "ER"
num_hidden_layers: 4
hidden_layer: 512

checkpoint_testing_episodes: 10
testing_episodes: 10
total_timesteps: 1000000
test_interval: 20000

save_trajectories: True
root_directory: "./sweep_dqn_vs_scenarios_5stack"
trajectory_path: "episodes"
model_save_path: "models"
