seed: 42

env_name: "crash-v0"
architecture: "DQN"
track: True
device: "cpu"
ego_model: "./models/train_vs_cutin.pth"

policy_A:
  - scenarios.IdleSlower
  - scenarios.IdleFaster
  - scenarios.CutIn
  - scenarios.CutInSlowDown
policy_B:
  - policies.MobilPolicy

frame_stack: 1
render: True
train_ego: False

# NN
batch_size: 32
gamma: 0.8
start_e: 1.0
end_e: 0.05
decay_e: 6000
tau: 0.005
lr: 0.0005
buffer_size: 15000
buffer_type: "ER"
num_hidden_layers: 1
hidden_layer: 256

total_episodes: 100
total_timesteps: 100000

save_trajectories: True
trajectory_path: "./mobil_vs_scenarios/episodes"
model_save_path: "./models/train_vs_cutin.pth"
