seed: 42

env_name: 'crash-v0'
architecture: 'DQN'
track: True
device: 'cpu'

# NN
batch_size: 32
gamma: 0.8
start_e: 1.0
end_e: 0.05
decay_e: 6000
tau: 0.005
lr: 0.0005
buffer_size: 100000
buffer_type: 'ER'
num_hidden_layers: 1
hidden_layer: 512

total_timesteps: 100000

save_trajectories: False
trajectory_path: "./trajectories"

model_folder: "./test_refactor"
